aviary_rise_node:
  ros__parameters:
    control_frequency: 50.0
    controller_type: noresnet
    d_out: 3
    desired_trajectory: 1
    hover_tolerance: 0.2
    is_gazebo: true
    k1: 1.743105460183871
    k2: 3.9387112810303218
    k3: 4.702155077385402
    k_rise: 0.5706739477628766
    mpc_acc_hor_max: 6.0
    mpc_acc_vert_max: 3.0
    odom_timeout_sec: 15.0
    plot: false
    q_e: 1.0
    r_u: 0.2
    safe_x_max: 5.0
    safe_y_max: 11.5
    safe_z_max: 0.5
    safe_z_min: -6.5
    settle_ticks: 50
    sim_time: 60.0
    traj1_alpha_warp: 0.5
    traj1_center_z: -0.75
    traj1_period: 30.0
    traj1_x_amp: 1.5
    traj1_y_amp: 3.0
    traj1_z_amp: 0.25
    traj2_center_z: -0.5
    traj2_petal_radius: 2.5
    traj2_target_speed: 1.0
    vehicle_name: px4_1
    w_fail: 1000.0
    watchdog_freq: 10.0
    windup_time_sec: 5.0
