aviary_rise_node:
  ros__parameters:
    control_frequency: 50.0
    controller_type: noresnet
    d_in: 15
    d_out: 3
    desired_trajectory: 2
    h_act_func: swish
    initial_weight_scale_factor: 0.1
    init_tol: 0.2
    init_x: 0.70
    init_y: -2.37
    init_z: -1.5
    k_1: 0.1250013535217034
    k_2: 0.8987431755260068
    k_3: 3.647668260273761
    k_rise: 0.9771171288636008
    o_act_func: tanh
    q_e: 1.0
    r_u: 0.2
    safe_x_max: 5.0
    safe_y_max: 11.5
    safe_z_max: 0.5
    safe_z_min: -6.5
    save_data: false
    shortcut_act_func: swish
    sim_time: 60.0
    theta_bar: 1000000.0
    traj1_alpha_warp: 0.5
    traj1_center_z: -0.75
    traj1_period: 30.0
    traj1_x_amp: 1.5
    traj1_y_amp: 3.0
    traj1_z_amp: 0.25
    traj2_center_z: -0.5
    traj2_petal_radius: 2.5
    traj2_target_speed: 1.0
    w_fail: 1000.0
    xy_rand_range: 1.0    # +/- meters variation for takeoff X and Y
    z_rand_range: 0.25    # +/- meters variation for hover_start_z
