import sys
import pandas as pd
import matplotlib.pyplot as plt

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 plot_trial.py <path_to_csv>")
        sys.exit(1)

    csv_file = sys.argv[1]
    
    try:
        # Read the CSV generated by the Docker node
        data = pd.read_csv(csv_file)
        
        # Identify if weight columns exist
        weight_cols = [col for col in data.columns if col.startswith('W')]
        
        # Setup subplot architecture based on controller type
        if weight_cols:
            fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 10), sharex=True)
        else:
            fig, ax1 = plt.subplots(figsize=(10, 6))
            ax2 = None
        
        # Plot 1: Tracking Error Norm
        ax1.plot(data['Time_s'], data['Error_Norm_m'], 'b-', linewidth=2)
        ax1.set_title(f"Tracking Error Norm ||e(t)|| - {csv_file}")
        ax1.set_ylabel("Error Norm (m)")
        ax1.grid(True)
        
        if not ax2:
            ax1.set_xlabel("Time (s)")
            
        # Plot 2: Weight Convergence (If ResNet was active)
        if ax2 and weight_cols:
            for col in weight_cols:
                ax2.plot(data['Time_s'], data[col], linewidth=1, alpha=0.7)
            ax2.set_title("ResNet Parameter Convergence")
            ax2.set_xlabel("Time (s)")
            ax2.set_ylabel("Weight Value")
            ax2.grid(True)
        
        plt.tight_layout()
        
        # Save the plot next to the CSV
        output_png = csv_file.replace('.csv', '.png')
        plt.savefig(output_png)
        print(f"[*] Plot saved successfully to {output_png}")
        
    except Exception as e:
        print(f"[!] Error processing {csv_file}: {e}")

if __name__ == "__main__":
    main()