aviary_rise_node:
  ros__parameters:
    control_frequency: 50.0
    controller_type: supertwisting
    d_out: 3
    desired_trajectory: 1
    h_act_func: swish
    init_tol: 0.2
    init_z: -0.75
    is_gazebo: false
    k_1: 0.72
    k_2: 0.11
    k_3: 2.4
    k_rise: 0.5
    mpc_acc_hor_max: 6.0
    mpc_acc_vert_max: 6.0
    o_act_func: tanh
    odom_timeout_sec: 2.0
    q_e: 1.0
    r_u: 0.2
    safe_x_max: 5.0
    safe_y_max: 11.5
    safe_z_max: 0.5
    safe_z_min: -6.5
    save_data: true
    settle_ticks: 50
    shortcut_act_func: swish
    sim_time: 60.0
    theta_bar: 1000000.0
    traj1_alpha_warp: 0.5
    traj1_center_z: -0.75
    traj1_period: 30.0
    traj1_x_amp: 1.5
    traj1_y_amp: 3.0
    traj1_z_amp: 0.25
    traj2_center_z: -0.5
    traj2_petal_radius: 2.5
    traj2_target_speed: 1.5
    vehicle_name: sentinel5
    w_fail: 1000.0
    watchdog_freq: 10.0
