aviary_rise_node:
  ros__parameters:
    control_frequency_hz: 50.0
    controller_type: developed
    d_in: 15
    d_out: 3
    desired_trajectory: 1
    gamma: 10.0
    h_act_func: swish
    h_method: xavier
    hover_start_z_m_ned_aviary: -0.75
    initial_weight_scale_factor: 0.2
    init_tol_m: 0.2
    traj1_init_x_m_ned_aviary: 1.22
    traj1_init_y_m_ned_aviary: 3.87
    traj2_init_x_m_ned_aviary: 0.70
    traj2_init_y_m_ned_aviary: -2.37
    init_z_m_ned_aviary: -0.75
    init_yaw_deg: 0.0
    yaw_des_deg: 0.0
    k_1: 0.72
    k_2: 0.11
    k_3: 2.4
    k_rise: 0.5
    K_P_yaw: 2.0
    o_act_func: tanh
    o_method: he
    q_e: 1.0
    r_u: 0.2
    safe_x_min_m_ned_aviary: -5.0
    safe_x_max_m_ned_aviary: 5.0
    safe_y_min_m_ned_aviary: -11.5
    safe_y_max_m_ned_aviary: 11.5
    safe_z_max_m_ned_aviary: 0.5
    safe_z_min_m_ned_aviary: -6.5
    save_data: false
    shortcut_act_func: swish
    sim_length_s: 30.0  # edited
    sim_speed: 0.0 # 0.0 for "as fast possible"
    sigma_mod: 3.0
    theta_bar: 1000000.0
    traj1_alpha_warp: 0.5
    traj1_center_z_m_ned_aviary: -1.5
    traj1_period_s: 15.0 # edited
    traj1_x_amp_m_ned_aviary: 1.5
    traj1_y_amp_m_ned_aviary: 3.0
    traj1_z_amp_m_ned_aviary: 0.25
    traj2_center_z_m_ned_aviary: -1.5
    traj2_petal_radius_m: 2.5
    traj2_target_speed_mps: 1.5
    w_fail: 1000.0
    takeoff_timeout_s: 10.0
    xy_rand_range_m: 1.0    # +/- variation for takeoff X and Y in mini-batches
    z_rand_range_m: 0.0    # +/- variation for hover_start_z in mini-batches
    mpc_acc_hor_max_mps2: 6.0
    mpc_acc_vert_max_mps2: 3.0
    num_eval_seeds: 3 # For mini-batches in optimization.py
    base_seed: 42
    stage2_base_gains: "1A" # Which baseline stage to use for Stage 2 (1A or 1B)
    db_path: "sqlite:///output/optimization.db"
